config/routes.rb
Rails.application.routes.draw do
  resources :oauth_clients
  devise_for :users
  devise_scope :user do
    get "signup", to: "devise/registrations#new"
    get "login", to: "devise/sessions#new"
    get "logout", to: "sessions#destroy"
  end

  authenticated :user do
    root 'home#index', as: :authenticated_root
  end

  unauthenticated do
    root to: 'devise/sessions#new'
    root 'devise/sessions#new', as: :unauthenticated_root
  end

  match '/auth/sso/authorize' => 'auth#authorize', via: :all
  match '/auth/sso/access_token' => 'auth#access_token', via: :all
  match '/auth/sso/user' => 'auth#user', via: :all
  match '/oauth/token' => 'auth#access_token', via: :all
end

app/models/oauth_client.rb
class OauthClient < ApplicationRecord
  before_validation :set_attributes

  validates :name, :presence => true 

  private
    def set_attributes
      if new_record?
        generate_app_id!
        generate_app_secret!
      end
    end

    def generate_app_id!
      begin
        self.app_id = SecureRandom.hex
      end while self.class.exists?(app_id: app_id)
    end

    def generate_app_secret!
      begin
        self.app_secret = SecureRandom.hex
      end while self.class.exists?(app_secret: app_secret)
    end

  private

  def jwt_secret_key(client_id)
    OauthClient.find_by(client_id: client_id).secret_key
  end
end

app/controllers/oauth_clients_controller.rb
class OauthClientsController < ApplicationController
  before_action :set_oauth_client, only: %i[ show edit update destroy ]
  before_action :authenticate_user!

  # GET /oauth_clients or /oauth_clients.json
  def index
    @oauth_clients = OauthClient.where(deleted_at: nil)
  end

  # GET /oauth_clients/1 or /oauth_clients/1.json
  def show
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                
  end

  # GET /oauth_clients/new
  def new
    @oauth_client = OauthClient.new
  end

  # GET /oauth_clients/1/edit
  def edit
    
  end

  # POST /oauth_clients or /oauth_clients.json
  def create
    
    @oauth_client = OauthClient.new(oauth_client_params)

    respond_to do |format|
      if @oauth_client.save
        format.html { redirect_to oauth_client_url(@oauth_client), notice: "Oauth client was successfully created." }
        format.json { render :show, status: :created, location: @oauth_client }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @oauth_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /oauth_clients/1 or /oauth_clients/1.json
  def update
    
    respond_to do |format|
      if @oauth_client.update(oauth_client_params)
        format.html { redirect_to oauth_client_url(@oauth_client), notice: "Oauth client was successfully updated." }
        format.json { render :show, status: :ok, location: @oauth_client }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @oauth_client.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /oauth_clients/1 or /oauth_clients/1.json
  def destroy
    @oauth_client.deleted_at = Time.now
    @oauth_client.save

    redirect_to oauth_clients_path
  end

  def generate_token(client)
    payload = { user_id: 1, exp: 1.hour.from_now.to_i }
    token = Jwt.encode(payload, OauthClient.jwt_secret_key(client), 'HS256')
    render json: { token: token }
  end

  def validate_token(client)
    token = params[:token]
    begin
      payload = Jwt.decode(token, OauthClient.jwt_secret_key(client), ['HS256'])
      render json: { payload: payload }
    rescue Jwt::VerificationError
      render json: { error: 'Token inválido' }, status: :unauthorized
    end
  end

  private
  # Use callbacks to share common setup or constraints between actions.
  def set_oauth_client
    
    @oauth_client = OauthClient.find(params[:id])
  end

    # Only allow a list of trusted parameters through.
  def oauth_client_params
    
    params.require(:oauth_client).permit(:name, :app_id, :app_secret)
  end

  def jwt_secret_key(client_id)
    OauthClient.find_by(client_id: client_id).secret_key
  end
end

app/helpers/oauth_clients_helper.rb
module OauthClientsHelper
    def self.jwt_secret_key(client_id)
        OauthClient.find_by(client_id: client_id).secret_key
    end    
end

app/views/oauth_clients/_form.html.erb
<%= form_with(model: oauth_client) do |form| %>
  <% if oauth_client.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(oauth_client.errors.count, "error") %> Erro:</h2>

      <ul>
        <% oauth_client.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class='mt-3'>
    <%= form.label :name, style: "display: block" %>
    <%= form.text_field :name %>
  </div>

  <div class='mt-3'>
    <%= form.submit %>
  </div>
<% end %>

app/views/oauth_clients/_oauth_client.html.erb
<div id="<%= dom_id oauth_client %>" class="container mt-5">
  <div class="card">
    <div class="card-header bg-primary text-white">
      <h4 class="mb-0">Detalhes do OAuth Client</h4>
    </div>
    <div class="card-body">
      <p>
        <strong>Nome:</strong>
        <span class="text-muted"><%= oauth_client.name %></span>
      </p>

      <p>
        <strong>App ID:</strong>
        <span class="text-muted"><%= oauth_client.app_id %></span>
      </p>

      <p>
        <strong>App Secret:</strong>
        <span class="text-muted"><%= oauth_client.app_secret %></span>
      </p>
    </div>
    <% if @oauth_client %>
      <div class="m-3">
        <%= link_to "Editar", edit_oauth_client_path(@oauth_client) %> |
        <%= link_to "Voltar", oauth_clients_path %> |
        <%= link_to "Deletar", oauth_client_path(@oauth_client), data: { turbo_method: :delete } %>
      </div>
    <% end %>
  </div>
</div>

app/views/oauth_clients/edit.html.erb
<h1>Editing oauth client</h1>

<%= render "form", oauth_client: @oauth_client %>

<br>

<div>
  <%= link_to "Show this oauth client", @oauth_client %> |
  <%= link_to "Back to oauth clients", oauth_clients_path %>
</div>

app/views/oauth_clients/index.html.erb
<div class='m-5'>

  <h1 class='m-3'>Oauth clients</h1>

  <div id="oauth_clients">
    <% @oauth_clients.each do |oauth_client| %>
      <%= render oauth_client %>
      <p class='m-3'>
        <%= link_to "Mais detalhes", oauth_client %>
      </p>
    <% end %>
  </div>
  <div class='m-3'>

  <%= link_to "Novo", new_oauth_client_path %>
  </div>
</div>

app/views/oauth_clients/new.html.erb
<div class='m-5'>
  <h1>Novo</h1>

  <%= render "form", oauth_client: @oauth_client %>

  <br>

  <div>
    <%= link_to "Voltar", oauth_clients_path %>
  </div>
</div>

app/views/oauth_clients/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @oauth_client %>